package core

import (
	"fmt"
	"regexp"
	"strings"

	"github.com/promptforge/promptforge/internal/templates"
)

func buildPlanContent(description string, templateName string) (string, error) {
	if templateName == "" {
		goalSection := "<!-- Describe the intended purpose and outcome of this prompt -->"
		if description != "" {
			goalSection = description
		}

		return fmt.Sprintf(`# Prompt Plan

## Goal
%s

## Constraints
<!-- List the limitations, rules, and boundaries that must be respected -->

## Out of Scope
<!-- Explicitly state what this prompt should NOT handle or address -->

---

Note: This file is human-readable and editable. It is NOT authoritative.
The authoritative artifact is prompt.ir.json, generated by 'promptforge compile'.
`, goalSection), nil
	}

	tmpl, err := templates.Get(templateName)
	if err != nil {
		return "", err
	}

	content := tmpl.Plan
	if description != "" {
		content = overrideGoalSection(content, description)
	}

	return content, nil
}

func overrideGoalSection(content string, description string) string {
	lines := strings.Split(content, "\n")
	var out []string
	inGoal := false
	goalHeaderRe := regexp.MustCompile(`(?i)^##\s+goal\s*$`)
	headerRe := regexp.MustCompile(`^##\s+`)

	for i := 0; i < len(lines); i++ {
		line := lines[i]
		if goalHeaderRe.MatchString(strings.TrimSpace(line)) {
			out = append(out, line)
			out = append(out, description, "")
			inGoal = true
			continue
		}

		if inGoal {
			if headerRe.MatchString(strings.TrimSpace(line)) || strings.TrimSpace(line) == "---" {
				inGoal = false
				out = append(out, line)
			}
			continue
		}

		out = append(out, line)
	}

	return strings.Join(out, "\n")
}
