const vscode = require('vscode');
const path = require('path');
const fs = require('fs');
const { exec } = require('child_process');

function activate(context) {
    // Command: Create new plan
    let newPlanDisposable = vscode.commands.registerCommand('promptforge.newPlan', async () => {
        const workspaceFolders = vscode.workspace.workspaceFolders;
        if (!workspaceFolders || workspaceFolders.length === 0) {
            vscode.window.showErrorMessage('No workspace folder open.');
            return;
        }

        // Ask for initial idea
        const idea = await vscode.window.showInputBox({
            prompt: 'Enter your rough idea for the prompt',
            placeHolder: 'e.g., "Create a chatbot that helps debug API errors"',
            validateInput: (value) => {
                if (!value || value.trim().length === 0) {
                    return 'Please enter an idea';
                }
                return null;
            }
        });

        if (!idea) {
            return;
        }

        const projectDir = workspaceFolders[0].uri.fsPath;
        const promptforgeDir = path.join(projectDir, 'promptforge');
        const planPath = path.join(promptforgeDir, 'plan.md');

        // Create directory if needed
        if (!fs.existsSync(promptforgeDir)) {
            fs.mkdirSync(promptforgeDir, { recursive: true });
        }

        // Check if plan already exists
        if (fs.existsSync(planPath)) {
            const overwrite = await vscode.window.showWarningMessage(
                'plan.md already exists. Overwrite?',
                { modal: true },
                'Yes', 'No'
            );
            if (overwrite !== 'Yes') {
                return;
            }
        }

        // Create plan.md with idea
        const planContent = `# Prompt Plan

## Goal
${idea}

## Constraints
<!-- List the limitations, rules, and boundaries that must be respected -->

## Out of Scope
<!-- Explicitly state what this prompt should NOT handle or address -->

---

Note: This file is human-readable and editable. It is NOT authoritative.
The authoritative artifact is prompt.ir.json, generated by 'promptforge compile'.
`;

        try {
            fs.writeFileSync(planPath, planContent, 'utf8');
            vscode.window.showInformationMessage('✅ Plan created! Opening editor...');
            
            // Open the editor
            const uri = vscode.Uri.file(planPath);
            vscode.commands.executeCommand('promptforge.openEditor', uri);
        } catch (error) {
            vscode.window.showErrorMessage(`Failed to create plan: ${error.message}`);
        }
    });

    // Command: Open editor
    let disposable = vscode.commands.registerCommand('promptforge.openEditor', async (uri) => {
        // Get the plan.md file path
        let filePath = uri?.fsPath;
        
        // If no file selected, try to find plan.md in workspace
        if (!filePath) {
            const workspaceFolders = vscode.workspace.workspaceFolders;
            if (workspaceFolders && workspaceFolders.length > 0) {
                const planPath = path.join(workspaceFolders[0].uri.fsPath, 'promptforge', 'plan.md');
                if (fs.existsSync(planPath)) {
                    filePath = planPath;
                } else {
                    vscode.window.showErrorMessage('plan.md not found. Run "promptforge init" first.');
                    return;
                }
            } else {
                vscode.window.showErrorMessage('No workspace folder open.');
                return;
            }
        }

        // Create and show webview panel
        const panel = vscode.window.createWebviewPanel(
            'promptforgeEditor',
            'PromptForge Plan Editor',
            vscode.ViewColumn.One,
            {
                enableScripts: true,
                retainContextWhenHidden: true
            }
        );

        // Read current plan.md content
        let currentContent = '';
        try {
            currentContent = fs.readFileSync(filePath, 'utf8');
        } catch (error) {
            vscode.window.showErrorMessage(`Error reading file: ${error.message}`);
        }

        // Parse markdown
        const goalMatch = currentContent.match(/## Goal\s*\n([\s\S]*?)(?=\n## |$)/);
        const constraintsMatch = currentContent.match(/## Constraints\s*\n([\s\S]*?)(?=\n## |$)/);
        const outOfScopeMatch = currentContent.match(/## Out of Scope\s*\n([\s\S]*?)(?=\n---|$)/);
        
        const commentRegex = /<!--[\s\S]*?-->/g;
        const goal = goalMatch ? goalMatch[1].trim().replace(commentRegex, '').trim() : '';
        const constraints = constraintsMatch ? constraintsMatch[1].trim().replace(commentRegex, '').trim() : '';
        const outOfScope = outOfScopeMatch ? outOfScopeMatch[1].trim().replace(commentRegex, '').trim() : '';

        // Set webview content
        panel.webview.html = getWebviewContent(goal, constraints, outOfScope, false);
        
        // Check if JSON already exists
        const projectDir = filePath ? path.dirname(path.dirname(filePath)) : 
            (vscode.workspace.workspaceFolders?.[0]?.uri.fsPath);
        if (projectDir) {
            const jsonPath = path.join(projectDir, 'prompt.ir.json');
            if (fs.existsSync(jsonPath)) {
                try {
                    const jsonContent = fs.readFileSync(jsonPath, 'utf8');
                    panel.webview.postMessage({
                        command: 'jsonGenerated',
                        json: jsonContent,
                        formatted: JSON.stringify(JSON.parse(jsonContent), null, 2)
                    });
                } catch (e) {
                    // Ignore
                }
            }
        }

        // Handle messages from webview
        panel.webview.onDidReceiveMessage(
            async message => {
                switch (message.command) {
                    case 'save':
                        await saveAndCompile(filePath, message.goal, message.constraints, message.outOfScope, panel);
                        break;
                    case 'openJSON':
                        const projectDir = path.dirname(path.dirname(filePath));
                        const jsonPath = path.join(projectDir, 'prompt.ir.json');
                        if (fs.existsSync(jsonPath)) {
                            const doc = await vscode.workspace.openTextDocument(jsonPath);
                            await vscode.window.showTextDocument(doc);
                        } else {
                            vscode.window.showWarningMessage('prompt.ir.json not found. Save your plan first.');
                        }
                        break;
                }
            },
            null,
            context.subscriptions
        );
    });

    context.subscriptions.push(disposable);
    context.subscriptions.push(newPlanDisposable);
}

async function saveAndCompile(filePath, goal, constraints, outOfScope, panel) {
    const markdown = `# Prompt Plan

## Goal
${goal || '<!-- Describe the intended purpose and outcome of this prompt -->'}

## Constraints
${constraints || '<!-- List the limitations, rules, and boundaries that must be respected -->'}

## Out of Scope
${outOfScope || '<!-- Explicitly state what this prompt should NOT handle or address -->'}

---

Note: This file is human-readable and editable. It is NOT authoritative.
The authoritative artifact is prompt.ir.json, generated by 'promptforge compile'.
`;

    try {
        // Save plan.md with better error handling
        try {
            fs.writeFileSync(filePath, markdown, 'utf8');
        } catch (writeError) {
            // Handle specific file system errors
            if (writeError.code === 'EACCES' || writeError.code === 'EPERM') {
                const errorMsg = `Permission denied: Cannot write to ${filePath}. Please check file permissions.`;
                vscode.window.showErrorMessage(errorMsg);
                panel.webview.postMessage({ command: 'error', message: errorMsg });
                return;
            } else if (writeError.code === 'ENOSPC') {
                const errorMsg = 'Disk full: Cannot save file. Please free up disk space.';
                vscode.window.showErrorMessage(errorMsg);
                panel.webview.postMessage({ command: 'error', message: errorMsg });
                return;
            } else if (writeError.code === 'ENOENT') {
                const errorMsg = `Directory not found: ${path.dirname(filePath)}. Please ensure the directory exists.`;
                vscode.window.showErrorMessage(errorMsg);
                panel.webview.postMessage({ command: 'error', message: errorMsg });
                return;
            }
            throw writeError; // Re-throw if not a known error
        }
        
        // Get project directory
        const projectDir = path.dirname(path.dirname(filePath));
        const outputPath = path.join(projectDir, 'prompt.ir.json');
        
        // Compile to JSON
        await compileToJSON(projectDir, outputPath, panel);
        
    } catch (error) {
        // Provide user-friendly error messages
        const errorMsg = error.message || 'An unexpected error occurred';
        vscode.window.showErrorMessage(`Failed to save plan: ${errorMsg}`);
        panel.webview.postMessage({ command: 'error', message: errorMsg });
    }
}

function compileToJSON(projectDir, outputPath, panel) {
    return new Promise((resolve, reject) => {
        // Find promptforge.exe - check common locations
        const possiblePaths = [
            'promptforge.exe',
            'promptforge',
            path.join(projectDir, 'promptforge.exe'),
            path.join(projectDir, '..', 'promptforge.exe'),
            path.join(projectDir, '..', '..', 'promptforge.exe'),
        ];
        
        // Try to find promptforge in PATH or project
        const promptforgeCmd = 'promptforge.exe';
        
        // Show progress indicator
        vscode.window.setStatusBarMessage('Compiling plan to JSON...', 2000);
        
        // Run compile command with timeout
        const timeout = 30000; // 30 seconds
        const compileProcess = exec(`"${promptforgeCmd}" compile`, { cwd: projectDir, timeout: timeout }, (error, stdout, stderr) => {
            // Read the generated JSON
            try {
                if (fs.existsSync(outputPath)) {
                    // Check file permissions
                    try {
                        fs.accessSync(outputPath, fs.constants.R_OK);
                    } catch (accessError) {
                        const errorMsg = `Cannot read generated JSON file: ${outputPath}. Permission denied.`;
                        vscode.window.showErrorMessage(errorMsg);
                        panel.webview.postMessage({ command: 'error', message: errorMsg });
                        reject(new Error(errorMsg));
                        return;
                    }
                    
                    const jsonContent = fs.readFileSync(outputPath, 'utf8');
                    
                    // Validate JSON before parsing
                    let jsonData;
                    try {
                        jsonData = JSON.parse(jsonContent);
                    } catch (parseError) {
                        const errorMsg = `Invalid JSON generated: ${parseError.message}. The compilation may have failed.`;
                        vscode.window.showErrorMessage(errorMsg);
                        panel.webview.postMessage({ command: 'error', message: errorMsg });
                        reject(new Error(errorMsg));
                        return;
                    }
                    
                    // Send JSON to webview
                    panel.webview.postMessage({
                        command: 'jsonGenerated',
                        json: jsonContent,
                        formatted: JSON.stringify(jsonData, null, 2)
                    });
                    
                    vscode.window.setStatusBarMessage('✅ Plan saved and JSON generated!', 3000);
                    resolve();
                } else {
                    // CLI not found or compilation failed
                    if (error) {
                        // Check if it's a "command not found" error
                        if (error.code === 'ENOENT' || error.message.includes('not found') || error.message.includes('is not recognized')) {
                            const errorMsg = 'PromptForge CLI not found. Please install promptforge.exe and ensure it is in your PATH. Using default JSON structure.';
                            vscode.window.showWarningMessage(errorMsg);
                            
                            // Create a basic JSON structure as fallback
                            const basicJSON = {
                                system_role: "You are a deterministic assistant that follows strict rules and schemas.",
                                rules: [
                                    { id: "output-json", description: "Output must be valid JSON" },
                                    { id: "no-explanations", description: "Do not include explanations" },
                                    { id: "no-inference", description: "Do not infer missing values" },
                                    { id: "fail-ambiguity", description: "Fail on ambiguity" }
                                ],
                                input_schema: { type: "object", properties: {}, required: [] },
                                output_schema: { type: "object", properties: {}, required: [] },
                                failure_modes: [
                                    { id: "invalid-input", condition: "Input does not match input_schema", response: "Return error indicating schema validation failure" },
                                    { id: "ambiguous-request", condition: "Request cannot be unambiguously interpreted", response: "Return error indicating ambiguity" },
                                    { id: "missing-required", condition: "Required fields are missing from input", response: "Return error listing missing required fields" }
                                ]
                            };
                            
                            // Try to write basic JSON
                            try {
                                fs.writeFileSync(outputPath, JSON.stringify(basicJSON, null, 2), 'utf8');
                                panel.webview.postMessage({
                                    command: 'jsonGenerated',
                                    json: JSON.stringify(basicJSON, null, 2),
                                    formatted: JSON.stringify(basicJSON, null, 2)
                                });
                                vscode.window.setStatusBarMessage('✅ Plan saved! (Using default JSON - CLI not found)', 3000);
                                resolve();
                            } catch (writeError) {
                                const errorMsg = `Failed to write JSON file: ${writeError.message}`;
                                vscode.window.showErrorMessage(errorMsg);
                                panel.webview.postMessage({ command: 'error', message: errorMsg });
                                reject(new Error(errorMsg));
                            }
                            return;
                        }
                        
                        // Other compilation errors
                        const errorMsg = `Compilation failed: ${error.message}. ${stderr ? 'Details: ' + stderr : ''}`;
                        vscode.window.showErrorMessage(errorMsg);
                        panel.webview.postMessage({ command: 'error', message: errorMsg });
                        reject(new Error(errorMsg));
                        return;
                    }
                    
                    // File doesn't exist but no error - compilation may have failed silently
                    const errorMsg = 'Compilation completed but output file not found. Please check the compilation logs.';
                    vscode.window.showWarningMessage(errorMsg);
                    panel.webview.postMessage({ command: 'error', message: errorMsg });
                    reject(new Error(errorMsg));
                }
            } catch (readError) {
                // Handle file system errors
                let errorMsg = `Failed to read JSON: ${readError.message}`;
                if (readError.code === 'EACCES' || readError.code === 'EPERM') {
                    errorMsg = `Permission denied: Cannot read ${outputPath}. Please check file permissions.`;
                } else if (readError.code === 'ENOENT') {
                    errorMsg = `File not found: ${outputPath}. Compilation may have failed.`;
                }
                vscode.window.showErrorMessage(errorMsg);
                panel.webview.postMessage({ command: 'error', message: errorMsg });
                reject(new Error(errorMsg));
            }
        });
        
        // Handle process timeout
        setTimeout(() => {
            if (!compileProcess.killed) {
                compileProcess.kill();
                const errorMsg = 'Compilation timed out after 30 seconds. The process may be stuck.';
                vscode.window.showErrorMessage(errorMsg);
                panel.webview.postMessage({ command: 'error', message: errorMsg });
                reject(new Error(errorMsg));
            }
        }, timeout);
    });
}

function getWebviewContent(goal, constraints, outOfScope, showJson = true) {
    return `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>PromptForge Editor</title>
    <style>
        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
            padding: 20px;
            background: var(--vscode-editor-background);
            color: var(--vscode-editor-foreground);
        }
        .section {
            margin-bottom: 25px;
        }
        label {
            display: block;
            font-weight: 600;
            margin-bottom: 8px;
            color: var(--vscode-textLink-foreground);
            font-size: 14px;
        }
        .help-text {
            font-size: 11px;
            opacity: 0.7;
            margin-top: 4px;
            font-style: italic;
        }
        textarea {
            width: 100%;
            min-height: 100px;
            padding: 10px;
            border: 1px solid var(--vscode-input-border);
            background: var(--vscode-input-background);
            color: var(--vscode-input-foreground);
            border-radius: 4px;
            font-family: inherit;
            font-size: 14px;
            resize: vertical;
        }
        textarea:focus {
            outline: 1px solid var(--vscode-focusBorder);
        }
        .buttons {
            display: flex;
            gap: 10px;
            margin-top: 20px;
        }
        button {
            padding: 10px 20px;
            border: none;
            border-radius: 4px;
            cursor: pointer;
            font-weight: 600;
            font-size: 14px;
        }
        .btn-save {
            background: var(--vscode-button-background);
            color: var(--vscode-button-foreground);
        }
        .btn-save:hover {
            background: var(--vscode-button-hoverBackground);
        }
        .status {
            margin-top: 15px;
            padding: 10px;
            border-radius: 4px;
            display: none;
        }
        .status.success {
            background: var(--vscode-testing-iconPassed);
            color: white;
            display: block;
        }
        .status.error {
            background: var(--vscode-testing-iconFailed);
            color: white;
            display: block;
        }
    </style>
</head>
<body>
    <div style="margin-bottom: 20px;">
        <h2 style="margin: 0 0 5px 0; color: var(--vscode-textLink-foreground);">🎯 PromptForge</h2>
        <p style="margin: 0; font-size: 12px; opacity: 0.8;">Transform your ideas into AI-ready prompt contracts</p>
    </div>
    
    <div class="section">
        <label for="goal">🎯 Goal</label>
        <textarea id="goal" placeholder="Describe what you want the AI to do...&#10;&#10;Example: Create a chatbot that helps users debug API errors and provides code examples">${escapeHtml(goal)}</textarea>
        <div class="help-text">What should this prompt accomplish? Be specific about the purpose.</div>
    </div>

    <div class="section">
        <label for="constraints">⚖️ Constraints</label>
        <textarea id="constraints" placeholder="List the rules and limitations...&#10;&#10;Example:&#10;- Must provide code examples in Python and JavaScript&#10;- Must validate API endpoints before suggesting fixes&#10;- Must not execute code, only show examples">${escapeHtml(constraints)}</textarea>
        <div class="help-text">What rules must the AI follow? Write in simple terms, one per line.</div>
    </div>

    <div class="section">
        <label for="outOfScope">🚫 Out of Scope</label>
        <textarea id="outOfScope" placeholder="What should this prompt NOT handle?&#10;&#10;Example:&#10;- Does not handle authentication issues&#10;- Does not debug network connectivity problems&#10;- Does not support languages other than Python/JavaScript">${escapeHtml(outOfScope)}</textarea>
        <div class="help-text">What should the AI explicitly avoid? One item per line.</div>
    </div>

    <div class="buttons">
        <button class="btn-save" onclick="save()">💾 Save & Generate JSON</button>
    </div>

    <div id="status" class="status"></div>
    
    <div id="jsonSection" style="margin-top: 30px; display: none; border-top: 1px solid var(--vscode-input-border); padding-top: 20px;">
        <div style="display: flex; justify-content: space-between; align-items: center; margin-bottom: 10px;">
            <h3 style="margin: 0; color: var(--vscode-textLink-foreground);">📄 Generated JSON Contract</h3>
            <span style="font-size: 11px; opacity: 0.7;">Ready for AI Agents</span>
        </div>
        <textarea id="jsonOutput" readonly style="min-height: 350px; font-family: 'Courier New', monospace; font-size: 12px; background: var(--vscode-textCodeBlock-background); color: var(--vscode-textBlockQuote-foreground); border: 1px solid var(--vscode-input-border); border-radius: 4px; padding: 12px; line-height: 1.5;" placeholder="JSON will appear here after saving..."></textarea>
        <div style="margin-top: 12px; display: flex; gap: 10px; align-items: center;">
            <button onclick="copyJSON()" style="padding: 8px 16px; background: var(--vscode-button-background); color: var(--vscode-button-foreground); border: none; border-radius: 4px; cursor: pointer; font-weight: 600;">📋 Copy JSON</button>
            <button onclick="openJSONFile()" style="padding: 8px 16px; background: var(--vscode-button-secondaryBackground); color: var(--vscode-button-secondaryForeground); border: none; border-radius: 4px; cursor: pointer;">📂 Open File</button>
            <span id="copyStatus" style="margin-left: 10px; color: var(--vscode-textLink-foreground); font-size: 12px;"></span>
        </div>
        <div style="margin-top: 10px; padding: 10px; background: var(--vscode-textBlockQuote-background); border-left: 3px solid var(--vscode-textLink-foreground); border-radius: 2px; font-size: 11px; opacity: 0.9;">
            <strong>💡 Tip:</strong> Copy this JSON and use it with any AI agent or LLM. It contains all the rules, constraints, and failure modes extracted from your plan.
        </div>
    </div>

    <script>
        const vscode = acquireVsCodeApi();
        
        function save() {
            const goal = document.getElementById('goal').value;
            const constraints = document.getElementById('constraints').value;
            const outOfScope = document.getElementById('outOfScope').value;
            
            vscode.postMessage({
                command: 'save',
                goal: goal,
                constraints: constraints,
                outOfScope: outOfScope
            });
            
            showStatus('Saving...', 'success');
        }
        
        function showStatus(message, type) {
            const status = document.getElementById('status');
            status.textContent = message;
            status.className = 'status ' + type;
            setTimeout(() => {
                status.className = 'status';
            }, 3000);
        }
        
        function copyJSON() {
            const jsonOutput = document.getElementById('jsonOutput');
            jsonOutput.select();
            document.execCommand('copy');
            const copyStatus = document.getElementById('copyStatus');
            copyStatus.textContent = '✅ Copied to clipboard!';
            setTimeout(() => {
                copyStatus.textContent = '';
            }, 3000);
        }
        
        function openJSONFile() {
            vscode.postMessage({
                command: 'openJSON'
            });
        }
        
        // Listen for messages from extension
        window.addEventListener('message', event => {
            const message = event.data;
            switch (message.command) {
                case 'jsonGenerated':
                    const jsonSection = document.getElementById('jsonSection');
                    const jsonOutput = document.getElementById('jsonOutput');
                    jsonOutput.value = message.formatted;
                    jsonSection.style.display = 'block';
                    showStatus('✅ JSON generated successfully!', 'success');
                    break;
                case 'error':
                    showStatus('❌ ' + message.message, 'error');
                    break;
            }
        });
    </script>
</body>
</html>`;
}

function escapeHtml(text) {
    const map = {
        '&': '&amp;',
        '<': '&lt;',
        '>': '&gt;',
        '"': '&quot;',
        "'": '&#039;'
    };
    return text.replace(/[&<>"']/g, m => map[m]);
}

function deactivate() {}

module.exports = {
    activate,
    deactivate
};

